### ISSUE TITLE
Bild Issues & Proposals

### ISSUE THREAD

**Issue by beschoenen** [MapOnline/interactive#14]
- [x] Level -1 & -2 don't span the same area
- [x] Firefox shows scrollbars
- [x] Hotspot for icons is too small on mobile devices #10
- [x] The other half of the popover arrow is visible on either the left or right side of a popover (Fixed, https://github.com/MapOnline/interactive/pull/17/commits/fa87e6323a1b353fb27dff84eb50bab7f243d913)
- Windows Mobile
  - [x] Panning doesn't work (Won't fix, works on Windows Phone 10)
  - [x] Zooming doesn't work (Won't fix, works on Windows Phone 10) 
- Mobile
  - [ ] Pinch to zoom is buggy (Currently needs very small pinches) #22
  - [x] Can't scroll a web page when you move over the map (Already available, [Interact mode](https://github.com/MapOnline/interactive/blob/develop/docs.md#setup))
- [x] Mousemove event stays active after leaving the canvas (Fixed, 887fe63)
- [x] Popover doesn't have a close button
- [ ] Popovers can be partially out of view https://github.com/MapOnline/interactive/issues/20
- [x] Popovers are always centered on mobile (Won't fix, this is by design)
- [x] Font families Gotham, Helvetica and Arial (Won't fix, these are available in the tool. You can also use CSS to fix this in interactive, [style overriding](https://github.com/MapOnline/interactive/blob/develop/docs.md#style-overwriting))
- [x] Header and underlining for popups in the tool (Won't fix, these are available in the tool)
- [x] Home button (Fixed, 9c4a692)
- [x] Invisible layer over the map so scroll doesn't get captured (Already available, [Interact mode](https://github.com/MapOnline/interactive/blob/develop/docs.md#setup))
- [x] Theming of the interface (Already available, [style overriding](https://github.com/MapOnline/interactive/blob/develop/docs.md#style-overwriting))
- [x] Images and Videos in popups (Already available)
- [ ] Metatags for text (Feature request - see Trello)

**Comment by RobbertK** [comment]
Relocated some points to separate issues.
